version: '3.8'

services:
  db:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    networks:
      - kit_subnet

  app:
    build: ./app
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
    networks:
      - kit_subnet

networks:
  kit_subnet:
    ipam:
      config:
        - subnet: 10.0.0.0/8

volumes:
  pgdata:
